### ISSUE TITLE
For Android? 

### ISSUE THREAD

**Issue by ghost** [OmGamer3158/gemini-voice-Assistant#1]
Can I also run this Gemini assistant ( parsonal assistant) in my termux terminal ?

**Comment by OmGamer3158** [comment]
Termax is not supported but you can run in pydroid3 app(not sponsored)

**Comment by OmGamer3158** [comment]
Termax is not supported but you can run in pydroid3 app(not sponsored)

**Comment by ompatel3158** [comment]
> Termax is not supported but you can run in pydroid3 app(not sponsored)

**Comment by ghost** [comment]
> > Termax is not supported but you can run in pydroid3 app(not sponsored)
> 

Okay,
